spring:
  application:
    name: demo
  ai:
    chat:
      observations:
        include-completion: true
        include-prompt: true
    image:
      observations:
        include-prompt: true
    ollama:
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: llama3.2
          num-ctx: 4096
          temperature: 0.7
      embedding:
        options:
          model: nomic-embed-text
    openai:
      chat:
        enabled: false
        options:
          model: gpt-4o
          temperature: 0.7
      embedding:
        enabled: false
        options:
          model: text-embedding-3-small
          dimensions: 768
      image:
        enabled: false
        options:
          model: dall-e-3
    vectorstore:
      pgvector:
        dimensions: 768
        index-type: hnsw
        initialize-schema: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      service.name: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    logging:
      endpoint: "http://localhost:4318/v1/logs"
    tracing:
      endpoint: "http://localhost:4318/v1/traces"
